name: Publish Release to GitHub Packages

on:
  push:
    tags:
      - 'v*'

permissions:
  packages: write
  contents: write

jobs:
  publish-release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@nguyenhuuit'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Update package.json
        run: pnpm pkg set name="@nguyenhuuit/adventofcode"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build
        env:
          AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_API_KEY }}

      - name: Set version from tag
        id: set-version
        run: |
          # Remove 'v' prefix from tag name
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          pnpm version $TAG_VERSION --no-git-tag-version --allow-same-version
          
          # Set output for use in subsequent steps
          echo "version=$TAG_VERSION" >> $GITHUB_OUTPUT
          
          echo "Publishing version: $TAG_VERSION"

      - name: Publish to GitHub Packages
        run: pnpm publish --access public --tag canary --registry https://npm.pkg.github.com --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          name: "Release v${{ steps.set-version.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 