name: Publish Release to GitHub Packages

on:
  push:
    tags:
      - 'v*'

permissions:
  packages: write
  contents: write

jobs:
  publish-release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@nguyenhuuit'
          cache: 'npm'

      - name: Update package.json
        run: npm pkg set name="@nguyenhuuit/adventofcode"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Set version from tag
        id: set-version
        run: |
          # Remove 'v' prefix from tag name
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          # Get version from package.json
          PKG_VERSION=$(node -p "require('./package.json').version")
          
          echo "Tag version: $TAG_VERSION"
          echo "Package version: $PKG_VERSION"
          
          if [ "$TAG_VERSION" != "$PKG_VERSION" ]; then
            echo "Versions differ, updating package.json version"
            npm version $TAG_VERSION --no-git-tag-version
          else
            echo "Versions match, skipping npm version update"
          fi
          
          echo "Publishing version: $TAG_VERSION"

      - name: Publish to GitHub Packages
        run: npm publish --access public --tag canary --registry https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGE_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          name: "Release ${{ steps.set-version.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 